Blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('blogs.urls', namespace = 'blogs')),
    url(r'^users/', include('users.urls', namespace='users'))
]

blogs/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.posts, name='posts'),
    url(r'^novoPost/$', views.novoPost, name='novoPost'),
    url(r'^editPost/(?P<post_id>\d+)/$', views.editPost, name='editPost'),
	url(r'^detailPost/(?P<post_id>\d+)/$', views.detailPost, name='detailPost'),
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login
from . import views

urlpatterns = [
    #Página de login
    url(r'^login/$', login, {'template_name': 'users/login.html'}, name='login'),
    url(r'^register/$', views.register, name='register'),
    url(r'^logout/$', views.logoutViews, name='logout'),
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class BlogPost(models.Model):
    #Compos da tabela BlogPost
    titulo = models.CharField(max_length=200)
    texto = models.TextField()
    textResumo = models.TextField(max_length=400, null=True)
    dataAdd = models.DateTimeField(auto_now_add=True)
    usuario = models.ForeignKey(User)

    def __str__(self):
        return self.texto[:50] + '...'

users/models.py
from django.db import models

# Create your models here.

blogs/forms.py
from django import forms
from .models import BlogPost

class PostForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['titulo', 'texto']
        labels = {'titulo': 'Titulo' ,'texto':''}
        widgets = {'texto': forms.Textarea(attrs={'cols':80})}

blogs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from .models import BlogPost
from .forms import PostForm

# Create your views here.
def posts(request):
    posts = BlogPost.objects.order_by('-dataAdd')
    context = {'posts': posts}
    return render(request, 'blogs/posts.html', context)

@login_required
def novoPost(request):
    if request.method != 'POST':
        form = PostForm()
    else:
        form = PostForm(request.POST)
        if form.is_valid():
            novoPost = form.save(commit=False)
            novoPost.usuario = request.user
            novoPost.save()
            return HttpResponseRedirect(reverse('blogs:posts'))

    context = {'form':form}
    return render(request, 'blogs/novoPost.html', context)

@login_required
def editPost(request, post_id):
    post = BlogPost.objects.get(id = post_id)
    if post.usuario != request.user:
        raise Http404

    if request.method != 'POST':
        form = PostForm(instance=post)
    else:
        form = PostForm(instance=post, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('blogs:posts'))

    context = {'post': post, 'form': form}
    return render(request, 'blogs/editPost.html', context)

def detailPost(request, post_id):
	post = BlogPost.objects.get(id = post_id)
	context = {'post':post}
	return render(request, 'blogs/detailPost.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def logoutViews(request):
    logout(request)
    return HttpResponseRedirect(reverse('blogs:posts'))

def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data = request.POST)

        if form.is_valid():
            novoUsuario = form.save()
            authenticated_user = authenticate(username = novoUsuario.username,
                                              password = request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('blogs:posts'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

blogs/templates/blogs/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-COMPATIBLE" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Blog Clebson</title>

        {% bootstrap_css %}
        {% bootstrap_javascript %}

    </head>
    <body>
        <!--Static navbar -->
        <nav class="navbar navbar-default navbar-static-top">
            <div class="container">
		<div id="navbar" class="navbar-collapse collapse">
                    {% if user.is_authenticated %}
                        <ul class="nav navbar-nav navbar-right">
                            <li><a>Bem Vindo, {{ user.first_name }}</a></li>
                            <li><a href="{% url 'users:logout' %}">Sair</a></li>
                        </ul>
                    {% else %}
                        <ul class="nav navbar-nav navbar-right">
                            <li><a href="{% url 'users:register'%}">Registrar</a></li>
                            <li><a href="{% url 'users:login' %}">Entrar</a></li>
                        </ul>
                    {% endif %}
			
                </div><!--/.nav-collapse -->
		
            </div>
        </nav>
	
		<div class="container">
			<header class="row">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h1>Clebson Carvalho</h1>
				<a href="{% url 'blogs:posts' %}">Home</a>
				<a href="{% url 'blogs:posts' %}"> - XXXXXX</a>
				<a href="{% url 'blogs:posts' %}"> - YYYYYY</a>
				<a href="{% url 'blogs:posts' %}"> - Contato</a>
				<a href="{% url 'blogs:posts' %}"> - Sobre</a>
					<button type="button" class="navbar-toggle collapsed"
				    	data-toggle="collapse" data-target="#navbar"
				    	aria-expanded="false" aria-controls="navbar">
					</button>
				</div>
			</div>
			</header>
			<div class="row">
				<div role="main" class="col-md-6 col-md-push-3">
					{% block header %}
					{% endblock header %}
					{% block content %}
					{% endblock content %}
				</div>
				<aside role="complementary" class="col-md-3 col-md-push-3">
					<div class="panel panel-default">
			    		<div class="panel-heading">
							<h2>Fluid</h2>
						</div>
					</div>
				</aside>
				<nav class="col-md-3 col-md-pull-9">
					<div class="panel panel-default">
						<div class="panel-heading">
							<h2>Parceiros</h2>
						</div>
					</div>
				</nav>
			</div>
			<footer class="row">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h2>Parceiros</h2>
					</div>
				</div>
			</footer>
		</div>
    </body>
</html>

blogs/templates/blogs/detailPost.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}

{% block header %}
{% endblock header %}

{% block content %}
	<div class="panel panel-default">
        <div class="panel-heading">
            <h3>
                {{ post.titulo }}<a href="{% url 'blogs:editPost' post.id%}"><h5>Editar</h5></a>
            </h3>
            <h4>
                {{ post.dataAdd|date:'M d, Y H:i' }}
            </h4>
        </div>
        <div align="justify">
            <p>
                {{ post.texto|linebreaks }}
            </p>
        </div>
    </div>
{% endblock content %}

blogs/templates/blogs/editPost.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>
        Editar postagem
    </h2>
{% endblock header %}

{% block content %}
    <form action="{% url 'blogs:editPost' post.id %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Salvar</button>
        {% endbuttons %}
    </form>

{% endblock content %}

blogs/templates/blogs/novoPost.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>
        Adicionar postagem
    </h2>
{% endblock header %}


{% block content %}
    <form action="{% url 'blogs:novoPost' %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Salvar</button>
        {% endbuttons %}
    </form>
{% endblock content %}

blogs/templates/blogs/posts.html
{% extends "blogs/base.html" %}

{% block header %}
	<div class="panel panel-default">
            <div class="panel-heading">
    		<h2>Postagens</h2>
	    </div>
	</div>
{% endblock header %}

{% block content %}
    {% for post in posts %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>
                    <a href="{% url 'blogs:detailPost' post.id%}">{{ post.titulo }}</a>
                </h3>
                <h4>
                    {{ post.dataAdd|date:'M d, Y H:i' }}
                </h4>
            </div>
            <div align="justify">
                <p>
                    {{ post.textResumo|linebreaks }}
                </p>
            </div>
        </div>
    {% empty %}
        <h5>
            Sem postagens.
        </h5>
    {% endfor %}
{% endblock content%}

users/templates/users/login.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>
        Log in
    </h2>
{% endblock header %}

{% block content %}
    <form action="{% url 'users:login' %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Log in</button>
        {% endbuttons %}
        <input type="hidden" name="next" value="{% url 'blogs:posts' %}"/>
    </form>
{% endblock content %}

users/templates/users/register.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>
        Register
    </h2>
{% endblock header %}

{% block content %}
    <form action="{% url 'users:register' %}" method="post" class="form">
        {% csrf_token %}
        {% bootstrap_form form %}
        {% buttons %}
            <button name="submit" class="btn btn-primary">Register</button>
        {% endbuttons %}
        <input type="hidden" name="next" value="{% url 'blogs:posts' %}"/>
    </form>
{% endblock content %}